#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2014 Cédric Picard
#
# LICENSE
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# END_OF_LICENSE
#
"""
XKCD comics

Usage: xkcd.py [-d] XKCD

Options:
    -d, --download  Download corresponding xkcd.

Argument:
    XKCD    If it is a number, prints the title and the transcript of the
            corresponding xkcd.
            Otherwise, performs a research to find the corresponding xkcds.
"""


import sys
import re
import requests
from bs4 import BeautifulSoup
from docopt import docopt


def download(soup):
    number = soup.text[soup.text.index("http://xkcd.com"):]
    number = number.splitlines()[0].split("/")[-2]

    src_re = re.compile(r'^<.* src="([^"]+/([^"/]+))" .*>$')
    url_line = soup.findAll("img")[2]
    dl_url = url_line["src"]
    name = number + ": " + url_line["src"].split("/")[-1]

    r = requests.get(dl_url)
    open(name, "wb").write(r.content)


def search(query):
    title_re = re.compile(r"<a [^>]+/([0-9]+)/[^>]+>([^<]+)<.+><br ?/>")
    r = requests.get("http://xkcd.com/archive/")
    titles = title_re.findall(r.content)

    for item in titles:
        if query.lower() in item[1].lower():
            yield "[" + item[0] + "]\t" + item[1]


def transcript(soup):
    title = soup.title.string[6:]
    transcript = soup.find(id="transcript").string

    return title + "\n" +  "=" * len(title) + "\n\n" + transcript


def main():
    args = docopt(__doc__)
    xkcd = args['XKCD']

    if re.match(r"^[0-9]+$", xkcd):
        r = requests.get("http://xkcd.com/" + str(xkcd))

        if r.status_code == 404:
            print("XKCD not found: %s" % xkcd)
            sys.exit(1)

        page = r.text
        soup = BeautifulSoup(page)

        if args['--download']:
            download(soup)
        else:
            print(transcript(soup))

    else:
        for each in search(xkcd):
            print(each)


if __name__ == "__main__":
    main()
